apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: zone-ingress
  namespace: zoneprinter
  # optional annotation to apply static IP to LB
  annotations:
    networking.gke.io/static-ip: $MCI_IP
spec:
  template:
    spec:
      backend:
        serviceName: zone-mcs
        servicePort: 8080
